source "https://gems.ruby-china.com"

gem "jekyll", "3.9.0"
gem "jekyll-theme-primer"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-titles-from-headings"
gem "jekyll-relative-links"
gem "jekyll-default-layout"
gem "kramdown-parser-gfm"
gem "kramdown"
